config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  match 'users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], as: :finish_signup

  root 'homepage#index'
  get 'about' => 'homepage#about'
  get 'matching_items/:id' => 'items#matching', as: 'matching_items'

  resources :users, only: [:new, :create]
    resources :items

  resources :items, only:[:index, :show]
  resources :categories, only: [:show]
  resources :tags, only: [:show]

  namespace :admin do
    root to: 'admin#index'

    resources :categories, except: [:show, :edit, :update]
    resources :tags
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  TEMP_EMAIL_PREFIX = 'change@me'
  TEMP_EMAIL_REGEX = /\Achange@me/
  has_many :items
  
  devise :database_authenticatable, :omniauthable, :registerable, 
         :confirmable, :recoverable, :rememberable, :trackable, :validatable

  validates :email, format: { without: TEMP_EMAIL_REGEX }, on: :update

  accepts_nested_attributes_for :items

  def self.find_for_oauth(auth, signed_in_resource = nil)
    identity = Identity.find_for_oauth(auth)
    user = signed_in_resource ? signed_in_resource : identity.user
    if user.nil?
      #get existing user by email if the provider gives a verified email
      #if no verified email, assign a temporary email and ask for verification
      email_is_verified = auth.info.email && (auth.info.verified || auth.info.verified_email)
      email = auth.info.email if email_is_verified
      user = User.where(email: email).first if email

      #create user if it a new registration
      if user.nil?
        user = User.new(
          email: email ? email : "#{TEMP_EMAIL_PREFIX}-#{auth.id}-#{auth.provider.com}",
          password: Devise.friendly_token[0,20]
        )
        user.skip_confirmation!
        user.save!
      end
    end

    if identity.user != user
      identity.user = user
      identity.save!
    end
    user
  end

  def email_verified?
    self.email && self.email !~ TEMP_EMAIL_REGEX
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def show
    # authorize! :read, @user
  end

  def edit
    # authorize! :update, @user
  end

  def update
    # authorize! :update, @user
  end

  def finish_signup
    #authorize! :update, @user
    if request.patch? && params[:user]
      if @user.update(user_params)
        @user.skip_reconfirmation!
        sign_in(@user, bypass: true)
        redirect_to @user, notice: "Profile updated"
      else
        @show_errors = true
      end
    end
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    accessible = [:email, :name]
    accessible << [:password, :password_confirmation] unless params[:user][:password].blank?
    params.require(:user).permit(accessible)
  end

end

app/views/users/finish_signup.haml
%div{class: "container", id: "add-email"}
  %h1 Add Email
  = form_for(current_user, as: 'user', url: finish_signup_url(current_user), html: {role: 'form'}) do |f|

    - if @show_errors && current_user.errors.any?
      #error_explanation
        current_user.errors.full_messages.each do |msg|
          = msg

    .form-group
      = f.label :email
      .controls
        = f.text_field :email, autofocus: true, value: '', class: 'form-control-input input-lg', placeholder: 'Example: email@me.com'
        %p{class: 'help-block'}
          Please confirm your email address.
      .actions
        = f.submit 'Continue', class: 'btn btn-primary'

app/views/users/new.haml
%ul
  = form_for @user do |f|
    - if flash[:error]
      %p
        %b= flash[:error]

      - @user.errors.full_messages.each do |msg|
        %li.question.error
          .question-title
            %p
              %b=msg

    %p
      = f.label :email
      = f.email_field :email
    %p
      = f.label :password
      = f.password_field :password

    %p.submit
      %button.finish{type: "submit"} Sign up