config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  match 'users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], as: :finish_signup

  root 'homepage#index'
  get 'about' => 'homepage#about'
  get 'matching_items/:id' => 'items#matching', as: 'matching_items'

  resources :users, only: [:new, :create]
    resources :items

  resources :items, only:[:index, :show]
  resources :categories, only: [:show]
  resources :tags, only: [:show]

  namespace :admin do
    root to: 'admin#index'

    resources :categories, except: [:show, :edit, :update]
    resources :tags
  end
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
  has_many :images

  validates :user, presence: true

  accepts_nested_attributes_for :images

  acts_as_taggable

  enum state: {
    initial: 0,
    lost: 1,
    found: 2,
    united: 3,
    archived: 4
  }

  def self.lost_items
    where(state: 1)
  end

  def self.found_items
    where(state: 2)
  end

  def self.recent
    Item.order(created_at: :desc).limit(5)
  end

  def self.united
    where(state: 3)
  end

  def profile
    images.first.thumbnail
  end

  def matches
    @opposite_state = lost? ? 2 : 1
    Item.tagged_with(tag_list, any: true).where(state: @opposite_state)
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]
  before_action :setup_item, only: [:show, :edit, :update, :destroy, :matching]

  def index
    @lost_items = Item.lost_items.order(created_at: :desc).
      paginate(:page => params[:page], :per_page => 10)
    @found_items = Item.found_items.order(created_at: :desc).
      paginate(:page => params[:page], :per_page => 10)
  end

  def new
    @item = current_user.items.build
    @images = @item.images.build
  end

  def create
    @item = current_user.items.build(item_params)
    if @item.save
        redirect_to matching_items_url(@item), notice: 'item was sucessfully created.'
    else
      render action: 'new'
    end
  end

  def edit
    if @item.user == current_user
      render :edit
    else
      redirect_to new_user_session_url
    end
  end

  def update
    if @item.user == current_user
      if @item.update(item_params)
        redirect_to @item, notice: 'Item was sucessfully updated.'
      else
        render action: 'edit'
      end
    else
      redirect_to new_user_session_url
    end
  end

  def destroy
    @item.destroy
    redirect_to items_url
  end

  def show
  end

  def matching
    @matches = @item.matches
  end

  private
  def setup_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:description, :user_id, :state, :category_id,
      :tag_list, images_attributes: [:source_file])
  end
end

app/helpers/item_helper.rb
module ItemHelper
  def opposite_state_of(item)
    item.lost? ? 'found' : 'lost'
  end
end

app/views/items/_form.haml
= form_for @item, html: { multipart: true } do |f|
  - if @item.errors.any?
    #error_explanation
      %h2 
        = pluralize(@item.errors.count, "error")
        prohibited this item from being saved

      %ul
        - @item.errors.full_messages.each do |msg|
          %li= msg

  = f.fields_for :images do |f|
    .form-group
      = f.label :source_file
      = f.file_field :source_file, class: "form-control"
  
  .form-group
    = f.label :description
    = f.text_field :description, class: "form-control"

  .form-group
    = f.label :state, 'Lost'
    = f.radio_button :state, 'lost', class: "form-control"
    = f.label :state, 'Found'
    = f.radio_button :state, 'found', class: "form-control"
  .form-group
    = f.label :category_id, 'Category'
    = f.select(:category_id, Category.all.collect {|cat| [ cat.name.capitalize, cat.id ] }, { include_blank: true })
  .form-group
    = f.label :tag_list, 'Tags (separated by commas)'
    = f.text_field :tag_list, class: "form-control"

  .form-group
    = f.submit 'Save item', class: "btn btn-primary"

app/views/items/_item.haml
.col-md-3
  %div{class: "box panel panel-default"}
    = link_to image_tag(item.profile), item 
    %div{class: "panel-body"}
      = item.description 

      %br 
      - if current_user && item.user == current_user 
        %div{class: "actions"}
          = link_to edit_item_url(item) do 
            %span{class: "fa fa-edit"} 
              Edit
          = link_to item, method: :delete, data: {confirm: 'Are you sure'} do 
            %span{class: "fa fa-trash"}
              Delete

      - if item.tag_list.count > 0
        %p 
          tags: 
          - item.tag_list.each do |tag|
            = link_to tag, tag_url(tag)

app/views/items/edit.haml
%h2
  New Item
= render 'form'
= link_to 'Back', items_url

app/views/items/index.haml
%h2 Lost Items
%div{id: "items", class: "transitions-enabled"}
  - @lost_items.each do |item| 
    = render partial: 'item', locals: { item: item }

%div{class: "center"}
  = will_paginate @lost_items, renderer: BootstrapPagination::Rails
  
%h2 Found Items
%div{id: "items", class: "transitions-enabled"}
  - @found_items.each do |item| 
    = render partial: 'item', locals: { item: item }

%div{class: "center"}
  = will_paginate @found_items, renderer: BootstrapPagination::Rails

app/views/items/matching.haml
- if @matches.any?
  %h4
    = opposite_state_of(@item).capitalize
    items matching
    = @item.description.capitalize

  %div{id: "items", class: "transitions-enabled"}
    - @matches.each do |item| 
      = render partial: 'item', locals: { item: item }
- else
  No items match 
  = @item.description

app/views/items/new.haml
%h2
  New Item
= render 'form'
= link_to 'Back', items_url

app/views/items/show.haml
= link_to 'Back', items_path
.row
  %div{class: "col-md-offset-2 col-md-8"} 
    %div{class: "panel panel-default"} 
      %div{class: "panel-heading center"}
        - if @item.images.any?
          - @item.images.each do |image|
            = image_tag image.thumbnail
            
      .panel-body
        %p 
          = @item.description

        - if @item.user == current_user
          = link_to edit_item_path(@item) do
            %span{class: "icon icon-edit"}
              Edit

          = link_to @item, method: :delete, data: {confirm: 'Are you sure'} do
            %span{class: "icon icon-trash"}
              Delete