config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  match 'users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], as: :finish_signup

  root 'homepage#index'
  get 'about' => 'homepage#about'
  get 'matching_items/:id' => 'items#matching', as: 'matching_items'

  resources :users, only: [:new, :create]
    resources :items

  resources :items, only:[:index, :show]
  resources :categories, only: [:show]
  resources :tags, only: [:show]

  namespace :admin do
    root to: 'admin#index'

    resources :categories, except: [:show, :edit, :update]
    resources :tags
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :items

  validates :name, presence: true
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < AdminController
  layout "admin"

  before_action :all_categories, only: [:index, :create]

  def index
    @category = Category.new
  end

  def create
    @category = Category.new(categories_params)
     
    if @category.save
      respond_to do |format|
        format.html
        format.js 
      end
    else
      flash[:error] = "Correct the errors as indicated"
      render :new
    end
  end

  private
  def categories_params
    params.require(:category).permit(:name)
  end

  def all_categories
    @categories = Category.all
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def show
    @category = Category.find(params[:id])
  end
end

app/views/admin/categories/_category.haml
%h4
  = link_to category_url(category.id) do
    = category.name.capitalize
    %span{class: "category_count"}
      = "(#{category.items.size})"

app/views/admin/categories/create.js.erb
$('.category-list').append("<%= j render 'category', category: @category %>")

app/views/admin/categories/index.haml
%div{class: "col-md-4 col-md-offset-2 category-list"}
  - @categories.each do |cat|
    = render partial: 'category', locals: {category: cat}

%div{class: "col-md-4"}
  .btn.btn-success.btn-sm.add-category
    Add a category

  .add-category-form
    = form_for [:admin, @category], remote: true, html: {class: "category disabled"} do |f|
      - if @category.errors.any? 
        #error_explanation
          %h2
            = pluralize(@category.errors.count, "error") 
            prohibited this category from being saved:

          %ul
            - @category.errors.full_messages.each do |msg| 
              %li
                = msg

      .category-add
        .form-group
          = f.label :name 
          = f.text_field :name, class: "form-control"
        .form-group
          .controls
            = f.submit '+ Add', class: 'btn btn-success save-category'
            .btn.btn-warning.category-cancel
              Cancel

app/views/admin/categories/new.haml
%h2 New Category

= form_for [:admin, @category], remote: true, html: {class: "disabled"} do |f|
  - if @category.errors.any? 
    #error_explanation
      %h2
        = pluralize(@category.errors.count, "error") 
        prohibited this category from being saved:

      %ul
        - @category.errors.full_messages.each do |msg| 
          %li
            = msg
  
  .form-group
    = f.label :name 
    = f.text_field :name, class: "form-control"
  .form-group
    .controls
      = f.button '+ Add', class: 'btn btn-success save loading-state'
      .btn.btn-warning.cancel.admin-cancel
        Cancel

= link_to 'Back', admin_categories_url