config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  match 'users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], as: :finish_signup

  root 'homepage#index'
  get 'about' => 'homepage#about'
  get 'matching_items/:id' => 'items#matching', as: 'matching_items'

  resources :users, only: [:new, :create]
    resources :items

  resources :items, only:[:index, :show]
  resources :categories, only: [:show]
  resources :tags, only: [:show]

  namespace :admin do
    root to: 'admin#index'

    resources :categories, except: [:show, :edit, :update]
    resources :tags
  end
end

app/views/layouts/_admin_header.haml
%nav{class: "admin navbar navbar-inverse navbar-default"}
  = link_to "Home", root_url, class: "navbar-brand", role: "navigation"

  %ul{class: "nav navbar-nav navbar-right"}

    %li 
      = link_to "Categories", admin_categories_url

    %li 
      = link_to "Tags", admin_tags_url
      

app/views/layouts/_footer.haml
%footer.footer
  %small
    This site has been created by
    = link_to "margOnline", "http://margonline.co.uk"

app/views/layouts/_header.haml
%nav{class: "navbar navbar-inverse navbar-default"}
  = link_to "Home", root_url, class: "navbar-brand"
  #bs-example-navbar-collapse-1{class: "collapse navbar-collapse"}
    %ul{class: "nav navbar-nav navbar-right"}
     
      %li= link_to "About", about_url 
      - if user_signed_in? && current_user.admin?
        %li= link_to "Add Category", new_admin_category_url
      - if user_signed_in? 
        %li= link_to "Log out", destroy_user_session_url, method: :delete
        %li= link_to "Add item", new_item_url
      - else
        %li= link_to "Sign up", new_user_registration_url
        %li= link_to "Sign in", new_user_session_url

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/admin.haml
!!!
/[if IE 8 ] <html lang="en" class="no-js ie8">
/[if IE 9 ] <html lang="en" class="no-js ie9">
/ [if (gt IE 9)|!(IE)]><!
%html.no-js{:lang => "en"}
  / <![endif]
  %head
    %title Lost &#38; Found
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
    = favicon_link_tag 'favicon.ico'
    %meta{ name: "HandheldFriendly", content: "True" }
    %meta{ content: "width=device-width, initial-scale=1", name: "viewport" }
    = render 'layouts/shim' 

  %body
    %div{class: "site-nav c9 med-c12"}
      .container
        = render 'layouts/admin_header' 
        = yield
        = render 'layouts/footer'

app/views/layouts/application.html.haml
!!!
/[if IE 8 ] <html lang="en" class="no-js ie8">
/[if IE 9 ] <html lang="en" class="no-js ie9">
/ [if (gt IE 9)|!(IE)]><!
%html.no-js{:lang => "en"}
  / <![endif]
  %head
    %title Lost &#38; Found
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
    = favicon_link_tag 'favicon.ico'
    %meta{ name: "HandheldFriendly", content: "True" }
    %meta{ content: "width=device-width, initial-scale=1", name: "viewport" }
    = render 'layouts/shim' 

  %body
    %div{class: "site-nav c9 med-c12"}
      .container
        = render 'layouts/header'
        .col-md-12
          .row
            = yield
            = render 'shared/tag_cloud'
            = render 'shared/categories'
        = render 'layouts/footer' 